import { NextResponse } from "next/server"

export interface User {
    id: number
    name: string
    age: number
}

const simpleUser: User[] = [{
    id: 1,
    name: 'simple',
    age: 1
}]
const heavyUser: User[] = [{
    "id": 1,
    "name": "Marge",
    "age": 19
  }, {
    "id": 2,
    "name": "Rubia",
    "age": 57
  }, {
    "id": 3,
    "name": "Abagael",
    "age": 60
  }, {
    "id": 4,
    "name": "Gerick",
    "age": 47
  }, {
    "id": 5,
    "name": "Xymenes",
    "age": 6
  }, {
    "id": 6,
    "name": "Lindsay",
    "age": 23
  }, {
    "id": 7,
    "name": "Sammy",
    "age": 83
  }, {
    "id": 8,
    "name": "Florri",
    "age": 94
  }, {
    "id": 9,
    "name": "Ginny",
    "age": 46
  }, {
    "id": 10,
    "name": "Sigismundo",
    "age": 13
  }, {
    "id": 11,
    "name": "Iorgos",
    "age": 11
  }, {
    "id": 12,
    "name": "Tuesday",
    "age": 92
  }, {
    "id": 13,
    "name": "Wernher",
    "age": 19
  }, {
    "id": 14,
    "name": "Kata",
    "age": 6
  }, {
    "id": 15,
    "name": "Brannon",
    "age": 58
  }, {
    "id": 16,
    "name": "Frederico",
    "age": 67
  }, {
    "id": 17,
    "name": "Suellen",
    "age": 40
  }, {
    "id": 18,
    "name": "Malinda",
    "age": 15
  }, {
    "id": 19,
    "name": "Keith",
    "age": 69
  }, {
    "id": 20,
    "name": "Katha",
    "age": 56
  }, {
    "id": 21,
    "name": "Hastings",
    "age": 15
  }, {
    "id": 22,
    "name": "Everett",
    "age": 21
  }, {
    "id": 23,
    "name": "Katusha",
    "age": 13
  }, {
    "id": 24,
    "name": "Lucita",
    "age": 5
  }, {
    "id": 25,
    "name": "Hanan",
    "age": 4
  }, {
    "id": 26,
    "name": "Gordy",
    "age": 78
  }, {
    "id": 27,
    "name": "Ashil",
    "age": 86
  }, {
    "id": 28,
    "name": "Brandyn",
    "age": 32
  }, {
    "id": 29,
    "name": "Chelsea",
    "age": 21
  }, {
    "id": 30,
    "name": "Mordy",
    "age": 16
  }, {
    "id": 31,
    "name": "Ursa",
    "age": 13
  }, {
    "id": 32,
    "name": "Shawna",
    "age": 24
  }, {
    "id": 33,
    "name": "Gavrielle",
    "age": 99
  }, {
    "id": 34,
    "name": "Guendolen",
    "age": 72
  }, {
    "id": 35,
    "name": "Sadye",
    "age": 47
  }, {
    "id": 36,
    "name": "Drusie",
    "age": 69
  }, {
    "id": 37,
    "name": "Caterina",
    "age": 98
  }, {
    "id": 38,
    "name": "Mariele",
    "age": 100
  }, {
    "id": 39,
    "name": "Zoe",
    "age": 61
  }, {
    "id": 40,
    "name": "Archie",
    "age": 100
  }, {
    "id": 41,
    "name": "Chase",
    "age": 34
  }, {
    "id": 42,
    "name": "Jedidiah",
    "age": 6
  }, {
    "id": 43,
    "name": "Henri",
    "age": 84
  }, {
    "id": 44,
    "name": "Levin",
    "age": 93
  }, {
    "id": 45,
    "name": "Fannie",
    "age": 24
  }, {
    "id": 46,
    "name": "Norri",
    "age": 6
  }, {
    "id": 47,
    "name": "Elbert",
    "age": 28
  }, {
    "id": 48,
    "name": "Corty",
    "age": 1
  }, {
    "id": 49,
    "name": "Howey",
    "age": 32
  }, {
    "id": 50,
    "name": "Trumaine",
    "age": 67
  }, {
    "id": 51,
    "name": "Quinn",
    "age": 99
  }, {
    "id": 52,
    "name": "Abby",
    "age": 9
  }, {
    "id": 53,
    "name": "Hodge",
    "age": 77
  }, {
    "id": 54,
    "name": "Nickey",
    "age": 99
  }, {
    "id": 55,
    "name": "Parrnell",
    "age": 86
  }, {
    "id": 56,
    "name": "Zorana",
    "age": 34
  }, {
    "id": 57,
    "name": "Damiano",
    "age": 70
  }, {
    "id": 58,
    "name": "Tome",
    "age": 87
  }, {
    "id": 59,
    "name": "Herb",
    "age": 93
  }, {
    "id": 60,
    "name": "Thorsten",
    "age": 51
  }, {
    "id": 61,
    "name": "Salomone",
    "age": 94
  }, {
    "id": 62,
    "name": "Davida",
    "age": 68
  }, {
    "id": 63,
    "name": "Lemmie",
    "age": 71
  }, {
    "id": 64,
    "name": "Harriet",
    "age": 31
  }, {
    "id": 65,
    "name": "Bibbie",
    "age": 63
  }, {
    "id": 66,
    "name": "Eberto",
    "age": 75
  }, {
    "id": 67,
    "name": "Rahel",
    "age": 4
  }, {
    "id": 68,
    "name": "Min",
    "age": 11
  }, {
    "id": 69,
    "name": "Nobie",
    "age": 54
  }, {
    "id": 70,
    "name": "Rosalind",
    "age": 17
  }, {
    "id": 71,
    "name": "Jourdain",
    "age": 61
  }, {
    "id": 72,
    "name": "Dulcy",
    "age": 62
  }, {
    "id": 73,
    "name": "Cosimo",
    "age": 25
  }, {
    "id": 74,
    "name": "Meade",
    "age": 28
  }, {
    "id": 75,
    "name": "Morten",
    "age": 39
  }, {
    "id": 76,
    "name": "Timi",
    "age": 5
  }, {
    "id": 77,
    "name": "Arlan",
    "age": 73
  }, {
    "id": 78,
    "name": "Madelin",
    "age": 83
  }, {
    "id": 79,
    "name": "Bekki",
    "age": 78
  }, {
    "id": 80,
    "name": "Devlin",
    "age": 97
  }, {
    "id": 81,
    "name": "Sigvard",
    "age": 65
  }, {
    "id": 82,
    "name": "Harriette",
    "age": 13
  }, {
    "id": 83,
    "name": "Gradey",
    "age": 71
  }, {
    "id": 84,
    "name": "Clare",
    "age": 90
  }, {
    "id": 85,
    "name": "Betty",
    "age": 65
  }, {
    "id": 86,
    "name": "Isidor",
    "age": 47
  }, {
    "id": 87,
    "name": "Lindy",
    "age": 85
  }, {
    "id": 88,
    "name": "Flin",
    "age": 24
  }, {
    "id": 89,
    "name": "Fremont",
    "age": 20
  }, {
    "id": 90,
    "name": "Heywood",
    "age": 49
  }, {
    "id": 91,
    "name": "Shirline",
    "age": 84
  }, {
    "id": 92,
    "name": "Fey",
    "age": 91
  }, {
    "id": 93,
    "name": "Anissa",
    "age": 4
  }, {
    "id": 94,
    "name": "Isabel",
    "age": 82
  }, {
    "id": 95,
    "name": "Marlo",
    "age": 18
  }, {
    "id": 96,
    "name": "Ethel",
    "age": 62
  }, {
    "id": 97,
    "name": "Marilin",
    "age": 33
  }, {
    "id": 98,
    "name": "Petrina",
    "age": 59
  }, {
    "id": 99,
    "name": "Codi",
    "age": 25
  }, {
    "id": 100,
    "name": "Carlina",
    "age": 10
  }]

export async function GET() {

   console.log("hit the GET") 

  return NextResponse.json(simpleUser)
}